// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blockers.sql

package db

import (
	"context"
	"database/sql"
)

const createBlocker = `-- name: CreateBlocker :one
INSERT INTO blockers (task_id, sub_task_id, reason, is_resolved)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at
`

type CreateBlockerParams struct {
	TaskID     sql.NullInt32 `json:"task_id"`
	SubTaskID  sql.NullInt32 `json:"sub_task_id"`
	Reason     string        `json:"reason"`
	IsResolved sql.NullBool  `json:"is_resolved"`
}

func (q *Queries) CreateBlocker(ctx context.Context, arg CreateBlockerParams) (Blocker, error) {
	row := q.db.QueryRowContext(ctx, createBlocker,
		arg.TaskID,
		arg.SubTaskID,
		arg.Reason,
		arg.IsResolved,
	)
	var i Blocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Reason,
		&i.IsResolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlocker = `-- name: DeleteBlocker :exec
DELETE FROM blockers
WHERE id = $1
`

func (q *Queries) DeleteBlocker(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBlocker, id)
	return err
}

const findAllBlockers = `-- name: FindAllBlockers :many
SELECT id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at FROM blockers
ORDER BY id
`

func (q *Queries) FindAllBlockers(ctx context.Context) ([]Blocker, error) {
	rows, err := q.db.QueryContext(ctx, findAllBlockers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocker
	for rows.Next() {
		var i Blocker
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubTaskID,
			&i.Reason,
			&i.IsResolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBlockerById = `-- name: FindBlockerById :one
SELECT id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at FROM blockers
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindBlockerById(ctx context.Context, id int32) (Blocker, error) {
	row := q.db.QueryRowContext(ctx, findBlockerById, id)
	var i Blocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Reason,
		&i.IsResolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findBlockersByTaskId = `-- name: FindBlockersByTaskId :many
SELECT id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at FROM blockers
WHERE task_id = $1
ORDER BY id
`

func (q *Queries) FindBlockersByTaskId(ctx context.Context, taskID sql.NullInt32) ([]Blocker, error) {
	rows, err := q.db.QueryContext(ctx, findBlockersByTaskId, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocker
	for rows.Next() {
		var i Blocker
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubTaskID,
			&i.Reason,
			&i.IsResolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBlockersByTaskIdAndSubTaskId = `-- name: FindBlockersByTaskIdAndSubTaskId :many
SELECT id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at FROM blockers
WHERE task_id = $1 AND (sub_task_id = $2 OR ($2 IS NULL AND sub_task_id IS NULL))
ORDER BY id
`

type FindBlockersByTaskIdAndSubTaskIdParams struct {
	TaskID    sql.NullInt32 `json:"task_id"`
	SubTaskID sql.NullInt32 `json:"sub_task_id"`
}

func (q *Queries) FindBlockersByTaskIdAndSubTaskId(ctx context.Context, arg FindBlockersByTaskIdAndSubTaskIdParams) ([]Blocker, error) {
	rows, err := q.db.QueryContext(ctx, findBlockersByTaskIdAndSubTaskId, arg.TaskID, arg.SubTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocker
	for rows.Next() {
		var i Blocker
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubTaskID,
			&i.Reason,
			&i.IsResolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlocker = `-- name: UpdateBlocker :one
UPDATE blockers
SET task_id = $2, sub_task_id = $3, reason = $4, is_resolved = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_id, sub_task_id, reason, is_resolved, created_at, updated_at
`

type UpdateBlockerParams struct {
	ID         int32         `json:"id"`
	TaskID     sql.NullInt32 `json:"task_id"`
	SubTaskID  sql.NullInt32 `json:"sub_task_id"`
	Reason     string        `json:"reason"`
	IsResolved sql.NullBool  `json:"is_resolved"`
}

func (q *Queries) UpdateBlocker(ctx context.Context, arg UpdateBlockerParams) (Blocker, error) {
	row := q.db.QueryRowContext(ctx, updateBlocker,
		arg.ID,
		arg.TaskID,
		arg.SubTaskID,
		arg.Reason,
		arg.IsResolved,
	)
	var i Blocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Reason,
		&i.IsResolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
