// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_sessions.sql

package db

import (
	"context"
	"time"
)

const createDailySession = `-- name: CreateDailySession :one
INSERT INTO daily_sessions (session_date, raw_notes_blob, generated_script)
VALUES ($1, $2, $3)
RETURNING id, session_date, raw_notes_blob, created_at, generated_script
`

type CreateDailySessionParams struct {
	SessionDate     time.Time `json:"session_date"`
	RawNotesBlob    string    `json:"raw_notes_blob"`
	GeneratedScript string    `json:"generated_script"`
}

func (q *Queries) CreateDailySession(ctx context.Context, arg CreateDailySessionParams) (DailySession, error) {
	row := q.db.QueryRowContext(ctx, createDailySession, arg.SessionDate, arg.RawNotesBlob, arg.GeneratedScript)
	var i DailySession
	err := row.Scan(
		&i.ID,
		&i.SessionDate,
		&i.RawNotesBlob,
		&i.CreatedAt,
		&i.GeneratedScript,
	)
	return i, err
}

const deleteDailySession = `-- name: DeleteDailySession :exec
DELETE FROM daily_sessions
WHERE id = $1
`

func (q *Queries) DeleteDailySession(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDailySession, id)
	return err
}

const findAllDailySessions = `-- name: FindAllDailySessions :many
SELECT id, session_date, raw_notes_blob, created_at, generated_script FROM daily_sessions
ORDER BY id
`

func (q *Queries) FindAllDailySessions(ctx context.Context) ([]DailySession, error) {
	rows, err := q.db.QueryContext(ctx, findAllDailySessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySession
	for rows.Next() {
		var i DailySession
		if err := rows.Scan(
			&i.ID,
			&i.SessionDate,
			&i.RawNotesBlob,
			&i.CreatedAt,
			&i.GeneratedScript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDailySessionById = `-- name: FindDailySessionById :one
SELECT id, session_date, raw_notes_blob, created_at, generated_script FROM daily_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindDailySessionById(ctx context.Context, id int32) (DailySession, error) {
	row := q.db.QueryRowContext(ctx, findDailySessionById, id)
	var i DailySession
	err := row.Scan(
		&i.ID,
		&i.SessionDate,
		&i.RawNotesBlob,
		&i.CreatedAt,
		&i.GeneratedScript,
	)
	return i, err
}
