// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Blocker struct {
	ID         int32         `json:"id"`
	TaskID     sql.NullInt32 `json:"task_id"`
	SubTaskID  sql.NullInt32 `json:"sub_task_id"`
	Reason     string        `json:"reason"`
	IsResolved sql.NullBool  `json:"is_resolved"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type DailySession struct {
	ID              int32     `json:"id"`
	SessionDate     time.Time `json:"session_date"`
	RawNotesBlob    string    `json:"raw_notes_blob"`
	CreatedAt       time.Time `json:"created_at"`
	GeneratedScript string    `json:"generated_script"`
}

type SubTask struct {
	ID          int32         `json:"id"`
	TaskID      sql.NullInt32 `json:"task_id"`
	Title       string        `json:"title"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	IsCompleted bool          `json:"is_completed"`
}

type Task struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TaskNote struct {
	ID        int32         `json:"id"`
	TaskID    sql.NullInt32 `json:"task_id"`
	SubTaskID sql.NullInt32 `json:"sub_task_id"`
	Content   string        `json:"content"`
	Category  string        `json:"category"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
