// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO task_notes (task_id, sub_task_id, content, category)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, sub_task_id, content, category, created_at, updated_at
`

type CreateNoteParams struct {
	TaskID    sql.NullInt32 `json:"task_id"`
	SubTaskID sql.NullInt32 `json:"sub_task_id"`
	Content   string        `json:"content"`
	Category  string        `json:"category"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (TaskNote, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.TaskID,
		arg.SubTaskID,
		arg.Content,
		arg.Category,
	)
	var i TaskNote
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM task_notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const findAllNotes = `-- name: FindAllNotes :many
SELECT id, task_id, sub_task_id, content, category, created_at, updated_at FROM task_notes
ORDER BY id
`

func (q *Queries) FindAllNotes(ctx context.Context) ([]TaskNote, error) {
	rows, err := q.db.QueryContext(ctx, findAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskNote
	for rows.Next() {
		var i TaskNote
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubTaskID,
			&i.Content,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNoteById = `-- name: FindNoteById :one
SELECT id, task_id, sub_task_id, content, category, created_at, updated_at FROM task_notes
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindNoteById(ctx context.Context, id int32) (TaskNote, error) {
	row := q.db.QueryRowContext(ctx, findNoteById, id)
	var i TaskNote
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findNotesByTaskId = `-- name: FindNotesByTaskId :many
SELECT id, task_id, sub_task_id, content, category, created_at, updated_at FROM task_notes
WHERE task_id = $1
ORDER BY id
`

func (q *Queries) FindNotesByTaskId(ctx context.Context, taskID sql.NullInt32) ([]TaskNote, error) {
	rows, err := q.db.QueryContext(ctx, findNotesByTaskId, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskNote
	for rows.Next() {
		var i TaskNote
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubTaskID,
			&i.Content,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE task_notes
SET task_id = $2, sub_task_id = $3, content = $4, category = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_id, sub_task_id, content, category, created_at, updated_at
`

type UpdateNoteParams struct {
	ID        int32         `json:"id"`
	TaskID    sql.NullInt32 `json:"task_id"`
	SubTaskID sql.NullInt32 `json:"sub_task_id"`
	Content   string        `json:"content"`
	Category  string        `json:"category"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (TaskNote, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.ID,
		arg.TaskID,
		arg.SubTaskID,
		arg.Content,
		arg.Category,
	)
	var i TaskNote
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubTaskID,
		&i.Content,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
