// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBlocker(ctx context.Context, arg CreateBlockerParams) (Blocker, error)
	CreateDailySession(ctx context.Context, arg CreateDailySessionParams) (DailySession, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (TaskNote, error)
	CreateSubTask(ctx context.Context, arg CreateSubTaskParams) (SubTask, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteBlocker(ctx context.Context, id int32) error
	DeleteDailySession(ctx context.Context, id int32) error
	DeleteNote(ctx context.Context, id int32) error
	DeleteSubTask(ctx context.Context, id int32) error
	DeleteTask(ctx context.Context, id int32) error
	FindAllBlockers(ctx context.Context) ([]Blocker, error)
	FindAllDailySessions(ctx context.Context) ([]DailySession, error)
	FindAllNotes(ctx context.Context) ([]TaskNote, error)
	FindAllSubTasks(ctx context.Context) ([]SubTask, error)
	FindAllTasks(ctx context.Context) ([]Task, error)
	FindBlockerById(ctx context.Context, id int32) (Blocker, error)
	FindBlockersByTaskId(ctx context.Context, taskID sql.NullInt32) ([]Blocker, error)
	FindBlockersByTaskIdAndSubTaskId(ctx context.Context, arg FindBlockersByTaskIdAndSubTaskIdParams) ([]Blocker, error)
	FindDailySessionById(ctx context.Context, id int32) (DailySession, error)
	FindNoteById(ctx context.Context, id int32) (TaskNote, error)
	FindNotesByTaskId(ctx context.Context, taskID sql.NullInt32) ([]TaskNote, error)
	FindSubTaskById(ctx context.Context, id int32) (SubTask, error)
	FindSubTasksByTaskId(ctx context.Context, taskID sql.NullInt32) ([]SubTask, error)
	FindTaskById(ctx context.Context, id int32) (Task, error)
	UpdateBlocker(ctx context.Context, arg UpdateBlockerParams) (Blocker, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (TaskNote, error)
	UpdateSubTask(ctx context.Context, arg UpdateSubTaskParams) (SubTask, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
