// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sub_tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createSubTask = `-- name: CreateSubTask :one
INSERT INTO sub_tasks (task_id, title, is_completed)
VALUES ($1, $2, $3)
RETURNING id, task_id, title, created_at, updated_at, is_completed
`

type CreateSubTaskParams struct {
	TaskID      sql.NullInt32 `json:"task_id"`
	Title       string        `json:"title"`
	IsCompleted bool          `json:"is_completed"`
}

func (q *Queries) CreateSubTask(ctx context.Context, arg CreateSubTaskParams) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, createSubTask, arg.TaskID, arg.Title, arg.IsCompleted)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompleted,
	)
	return i, err
}

const deleteSubTask = `-- name: DeleteSubTask :exec
DELETE FROM sub_tasks
WHERE id = $1
`

func (q *Queries) DeleteSubTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSubTask, id)
	return err
}

const findAllSubTasks = `-- name: FindAllSubTasks :many
SELECT id, task_id, title, created_at, updated_at, is_completed FROM sub_tasks
ORDER BY id
`

func (q *Queries) FindAllSubTasks(ctx context.Context) ([]SubTask, error) {
	rows, err := q.db.QueryContext(ctx, findAllSubTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubTask
	for rows.Next() {
		var i SubTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubTaskById = `-- name: FindSubTaskById :one
SELECT id, task_id, title, created_at, updated_at, is_completed FROM sub_tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindSubTaskById(ctx context.Context, id int32) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, findSubTaskById, id)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompleted,
	)
	return i, err
}

const findSubTasksByTaskId = `-- name: FindSubTasksByTaskId :many
SELECT id, task_id, title, created_at, updated_at, is_completed FROM sub_tasks
WHERE task_id = $1
ORDER BY id
`

func (q *Queries) FindSubTasksByTaskId(ctx context.Context, taskID sql.NullInt32) ([]SubTask, error) {
	rows, err := q.db.QueryContext(ctx, findSubTasksByTaskId, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubTask
	for rows.Next() {
		var i SubTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubTask = `-- name: UpdateSubTask :one
UPDATE sub_tasks
SET title = $2, is_completed = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_id, title, created_at, updated_at, is_completed
`

type UpdateSubTaskParams struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	IsCompleted bool   `json:"is_completed"`
}

func (q *Queries) UpdateSubTask(ctx context.Context, arg UpdateSubTaskParams) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, updateSubTask, arg.ID, arg.Title, arg.IsCompleted)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCompleted,
	)
	return i, err
}
